<?php

use App\Http\Controllers\Admin\EmailGroupController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\ApprovalQueueController;
use App\Http\Controllers\Auth\AzureAuthController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\SafetyPerformanceController;
use App\Http\Controllers\MasterData\Api\EmployeeController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\PublicApprovalController;
use App\Http\Controllers\UserController;
use App\Mail\SendEmail;
use App\Models\AccidentNotification;
use App\Models\InvestigationReport;
use App\Models\MasterData\BodyPart;
use App\Models\MasterData\Ccow;
use App\Models\MasterData\Company;
use App\Models\MasterData\Department;
use App\Models\MasterData\Gender;
use App\Models\MasterData\IncidentType;
use App\Models\MasterData\InjuryCondition;
use App\Models\MasterData\IntervalAge;
use App\Models\MasterData\IntervalExperience;
use App\Models\MasterData\InvestigationQuestion;
use App\Models\MasterData\Jabatan;
use App\Models\MasterData\JobFactor;
use App\Models\MasterData\Location;
use App\Models\MasterData\MobileEquipment;
use App\Models\MasterData\PersonalFactor;
use App\Models\MasterData\Recommendation;
use App\Models\MasterData\Source;
use App\Models\MasterData\Status;
use App\Models\MasterData\UnsafeAct;
use App\Models\MasterData\UnsafeCondition;
use App\Models\User;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Route;
use Inertia\Inertia;

// ── Public Routes ─────────────────────────────────────────────────────────────
Route::get('/', function () {
    return redirect()->route('login');
});

Route::get('/mail/send', function () {
    $data = [
        'subject' => 'Safety Email',
        'title' => 'Safety Email',
        'body' => 'Ini adalah email uji coba dari Tutorial Laravel: Send Email Via SMTP GMAIL',
    ];

    Mail::to('iamzerodevid@gmail.com')->send(new SendEmail($data));

});

// Accident Notification Public Approval
Route::prefix('public')->name('public.')->group(function () {
    Route::get('/approve/{uuid}', [PublicApprovalController::class, 'show'])->name('accident.show');
    Route::post('/approve/{uuid}', [PublicApprovalController::class, 'approve'])->name('accident.approve');
    Route::post('/return/{uuid}', [PublicApprovalController::class, 'return'])->name('accident.return');
});

// ── Auth Routes (via Laravel Breeze) ─────────────────────────────────────────
// These are auto-generated by Breeze. If using custom auth, define here:
//
// Route::get('/login', [AuthController::class, 'create'])->name('login');
// Route::post('/login', [AuthController::class, 'store']);
// Route::post('/logout', [AuthController::class, 'destroy'])->name('logout');

require __DIR__.'/auth.php';

// Azure Auth Routes
Route::get('/auth/azure', [AzureAuthController::class, 'redirectToAzure'])->name('azure.login');
Route::get('/auth/azure/callback', [AzureAuthController::class, 'handleAzureCallback']);

// ── Authenticated Routes ──────────────────────────────────────────────────────

Route::middleware(['auth', 'verified'])->group(function () {

    // Dashboard
    Route::get('/dashboard', [DashboardController::class, 'index'])
        ->name('dashboard');

    // Users
    // Route::resource('users', UserController::class);

    // Profile
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');

    // Admin Group
    Route::prefix('admin')->name('admin.')->group(function () {
        // User Admin
        Route::get('/user', function () {
            return Inertia::render('Admin/User/Index');
        })->name('user.index');

        // Role & Permission Management
        Route::resource('roles', RoleController::class);

        // Menu
        Route::get('/menu', function () {
            return Inertia::render('Admin/Menu/Index');
        })->name('admin.menu.index');

        // Email Groups
        Route::resource('email-groups', EmailGroupController::class);

    });

    // Master Data Group
    Route::prefix('master-data')->name('master-data.')->group(function () {
        Route::get('/', function () {
            return Inertia::render('MasterData/Index');
        })->name('index');
        Route::get('/ccow', function () {
            return Inertia::render('MasterData/Ccow/Index');
        });
        Route::get('/company', function () {
            return Inertia::render('MasterData/Company/Index');
        });
        Route::get('/department', function () {
            return Inertia::render('MasterData/Department/Index');
        });
        Route::get('/jabatan', function () {
            return Inertia::render('MasterData/Jabatan/Index');
        })->name('jabatan.index');
        Route::get('/shift', function () {
            return Inertia::render('MasterData/Shift/Index');
        })->name('shift.index');
        Route::get('/interval-time', function () {
            return Inertia::render('MasterData/IntervalTime/Index');
        })->name('interval-time.index');
        Route::get('/day', function () {
            return Inertia::render('MasterData/Day/Index');
        })->name('day.index');
        Route::get('/roster', function () {
            return Inertia::render('MasterData/Roster/Index');
        })->name('roster.index');
        Route::get('/gender', function () {
            return Inertia::render('MasterData/Gender/Index');
        })->name('gender.index');
        Route::get('/interval-age', function () {
            return Inertia::render('MasterData/IntervalAge/Index');
        })->name('interval-age.index');
        Route::get('/interval-experience', function () {
            return Inertia::render('MasterData/IntervalExperience/Index');
        })->name('interval-experience.index');
        Route::get('/incident-type', function () {
            return Inertia::render('MasterData/IncidentType/Index');
        })->name('incident-type.index');
        Route::get('/kriteria', function () {
            return Inertia::render('MasterData/Kriteria/Index');
        })->name('kriteria.index');
        Route::get('/report-type', function () {
            return Inertia::render('MasterData/ReportType/Index');
        })->name('report-type.index');
        Route::get('/status', function () {
            return Inertia::render('MasterData/Status/Index');
        })->name('status.index');
        Route::get('/injury-condition', function () {
            return Inertia::render('MasterData/InjuryCondition/Index');
        })->name('injury-condition.index');
        Route::get('/body-part', function () {
            return Inertia::render('MasterData/BodyPart/Index');
        })->name('body-part.index');
        Route::get('/recommendation', function () {
            return Inertia::render('MasterData/Recommendation/Index');
        })->name('recommendation.index');
        Route::get('/source', function () {
            return Inertia::render('MasterData/Source/Index');
        })->name('source.index');
        Route::get('/unsafe-act', function () {
            return Inertia::render('MasterData/UnsafeAct/Index');
        })->name('unsafe-act.index');
        Route::get('/unsafe-condition', function () {
            return Inertia::render('MasterData/UnsafeCondition/Index');
        })->name('unsafe-condition.index');
        Route::get('/personal-factor', function () {
            return Inertia::render('MasterData/PersonalFactor/Index');
        })->name('personal-factor.index');
        Route::get('/job-factor', function () {
            return Inertia::render('MasterData/JobFactor/Index');
        })->name('job-factor.index');
        Route::get('/location', function () {
            return Inertia::render('MasterData/Location/Index');
        })->name('location.index');
        Route::get('/employee', function () {
            return Inertia::render('MasterData/Employee/Index');
        })->name('employee.index');
        Route::get('/mobile-equipment', function () {
            return Inertia::render('MasterData/MobileEquipment/Index');
        })->name('mobile-equipment.index');
    });

    Route::prefix('accident-notification')->name('accident-notification.')->group(function () {
        Route::get('/', function () {
            $user = auth()->user();
            $isCrs = $user && (
                $user->hasRole('crs', 'CRS', 'superadmin', 'super-admin', 'admin', 'hse admin', 'hse_admin') ||
                ($user->employee && $user->employee->can_approve)
            );

            $query = AccidentNotification::with(['ccow', 'company', 'location', 'incidentType', 'photos', 'day']);

            // Filter data berdasarkan company_id jika bukan CRS/Approver
            if (! $isCrs && $user && $user->employee_id) {
                $query->where('company_id', $user->employee->company_id);
            }

            $data = $query->latest()->get();

            return Inertia::render('AccidentNotification/Index', [
                'accidentNotifications' => $data,
                'master' => [
                    'ccows' => Ccow::where('is_active', true)->get(),
                    'companies' => Company::where('is_active', true)->get(),
                    'locations' => Location::where('is_active', true)->get(),
                    'incidentTypes' => IncidentType::where('is_active', true)->get(),
                    'statuses' => Status::where('is_active', true)->get(),
                    'departments' => Department::where('is_active', true)->get(),
                    'genders' => Gender::where('is_active', true)->get(),
                    'intervalAges' => IntervalAge::where('is_active', true)->get(),
                    'intervalExperiences' => IntervalExperience::where('is_active', true)->get(),
                    'jabatans' => Jabatan::where('is_active', true)->get(),
                ],
            ]);
        })->name('index');
    });

    Route::prefix('analisa-kecelakaan')->name('analisa-kecelakaan.')->group(function () {
        Route::get('/', function () {
            $user = auth()->user();
            $isCrs = $user && (
                $user->hasRole('crs', 'CRS', 'superadmin', 'super-admin', 'admin', 'hse admin', 'hse_admin') ||
                ($user->employee && $user->employee->can_approve)
            );

            if (!$isCrs && !$user->is_administrator) {
                abort(403, 'Unauthorized action. LPKS/LPKL is only accessible by CRS, HSE Admin, and Approvers.');
            }

            $query = InvestigationReport::with([
                'accidentNotification.ccow',
                'accidentNotification.company',
                'accidentNotification.location',
                'accidentNotification.incidentType',
                'accidentNotification.department',
                'documents',
                'approvals.approvedBy',
                'mobileEquipment',
            ]);

            if (! $isCrs && $user && $user->employee_id) {
                $query->whereHas('accidentNotification', function ($q) use ($user) {
                    $q->where('company_id', $user->employee->company_id);
                });
            }

            $reports = $query->latest()->get();

            $approvedStatusId = \App\Models\MasterData\Status::where('name', 'Approved')->value('id') ?? 9;
            $inInvestigationStatusId = \App\Models\MasterData\Status::where('name', 'In Investigation')->value('id') ?? 3;
            $approvedNotificationsQuery = AccidentNotification::with([
                'ccow', 'company', 'location', 'incidentType', 'photos', 'department',
                'companyContractor', 'reporter', 'approver', 'status', 'day',
            ])
                // Tampilkan yang Approved (belum ada LPKS/LPKL) ATAU In Investigation (sudah ada LPKS/LPKL, untuk edit)
                ->whereIn('status_id', [$approvedStatusId, $inInvestigationStatusId]);

            if (! $isCrs && $user && $user->employee_id) {
                $approvedNotificationsQuery->where('company_id', $user->employee->company_id);
            }

            $approvedNotifications = $approvedNotificationsQuery->latest()->get();

            return Inertia::render('InvestigationReport/Index', [
                'investigationReports' => $reports,
                'approvedNotifications' => $approvedNotifications,
                'master' => [
                    'ccows' => Ccow::where('is_active', true)->get(),
                    'companies' => Company::where('is_active', true)->get(),
                    'locations' => Location::where('is_active', true)->get(),
                    'incidentTypes' => IncidentType::where('is_active', true)->get(),
                    'sources' => Source::where('is_active', true)->get(),
                    'intervalExperiences' => IntervalExperience::where('is_active', true)->get(),
                    'injuryConditions' => InjuryCondition::where('is_active', true)->get(),
                    'bodyParts' => BodyPart::where('is_active', true)->get(),
                    'unsafeActs' => UnsafeAct::where('is_active', true)->get(),
                    'unsafeConditions' => UnsafeCondition::where('is_active', true)->get(),
                    'personalFactors' => PersonalFactor::where('is_active', true)->get(),
                    'jobFactors' => JobFactor::where('is_active', true)->get(),
                    'recommendations' => Recommendation::where('is_active', true)->get(),
                    'investigationQuestions' => InvestigationQuestion::where('is_active', true)->get(),
                    'mobileEquipments' => MobileEquipment::where('is_active', true)->orderBy('sort_order')->get(),
                ],
            ]);
        })->name('index');
    });

    Route::prefix('pica')->name('pica.')->group(function () {
        Route::get('/', function () {
            return Inertia::render('Pica/Index');
        })->name('index');
    });

    Route::prefix('safety-performance')->name('safety-performance.')->group(function () {
        Route::get('/', [SafetyPerformanceController::class, 'index'])->name('index');
        Route::get('/export', [SafetyPerformanceController::class, 'export'])->name('export');
    });

    // Approval Queue - Dashboard Approval
    Route::get('/approval-queue', [ApprovalQueueController::class, 'index'])->name('approval-queue.index');

    // Master Data Employee (API for Select2/Autocomplete)
    Route::get('/employees/search', [EmployeeController::class, 'search'])->name('employees.search');
});

Route::get('/auth/bypass-login', function () {
    if (app()->environment('local')) {
        $user = User::first();
        if ($user) {
            auth()->login($user);

            return redirect('/dashboard');
        }
    }

    return 'No user found or not in local environment';
});
